autoload, "frim.i",
    frim_error,
    frim_gen_2d,
    frim_gen_2d_random,
    frim_int_2d,
    frim_lane,
    frim_new_2d_linop,
    frim_region_2d,
    kolmogorov_covariance,
    kolmogorov_lane,
    kolmogorov_random,
    strehl_ratio,phase_variance,
    structure_function,
    wfs_model1;
